export const APS_BROWSER_DATA_RECEIVED = 'auth/aps/BROWSER_TOKEN_RECEIVED';
export const APS_SET_AUTO_REFRESH = 'auth/aps/SET_AUTO_REFRESH';
export const APS_TOKEN_REFRESH_START = 'auth/aps/TOKEN_REFRESH_START';
export const APS_TOKEN_REFRESH_ERROR = 'auth/aps/TOKEN_REFRESH_ERROR';
export const APS_TOKEN_REFRESH_END = 'auth/aps/TOKEN_REFRESH_END';
export const APS_TOKEN_CHANGED = 'auth/aps/TOKEN_CHANGED';
export const APS_SET_TOKEN_EXPIRED = 'auth/aps/SET_TOKEN_EXPIRED';
